export enum Configuration {
  PORT = 'PORT',
  DB_PORT = 'DB_PORT',
  DB_HOST = 'DB_HOST',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
  DB_TYPE = 'DB_TYPE',

  JWT_SECRET='JWT_SECRET',
}